/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillasRouteImport } from './routes/villas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as LandRouteImport } from './routes/land'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VillasRoute = VillasRouteImport.update({
  id: '/villas',
  path: '/villas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/land': typeof LandRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villas': typeof VillasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/land': typeof LandRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villas': typeof VillasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/land': typeof LandRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/villas': typeof VillasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/land'
    | '/properties'
    | '/sitemap.xml'
    | '/villas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/land'
    | '/properties'
    | '/sitemap.xml'
    | '/villas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/land'
    | '/properties'
    | '/sitemap.xml'
    | '/villas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LandRoute: typeof LandRoute
  PropertiesRoute: typeof PropertiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VillasRoute: typeof VillasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villas': {
      id: '/villas'
      path: '/villas'
      fullPath: '/villas'
      preLoaderRoute: typeof VillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LandRoute: LandRoute,
  PropertiesRoute: PropertiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VillasRoute: VillasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
